app:
  name: cloud
  domain: example.org

# storage limit for nextcloud files and database
storage:
  limits:
    data: 128Gi
    database: 128Gi

# you can change this values if you want
database:
  password: "secret#password"
  root_password: "very123secret#passWord!"
