apiVersion: v1
kind: Service
metadata:
  name: {{ include "team-chat.name" . }}-rc
spec:
  ports:
    - protocol: TCP
      name: web
      port: 3000
      targetPort: 3000
  selector:
    app: {{ include "team-chat.name" . }}-rc
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "team-chat.name" . }}-mongo
spec:
  ports:
    - protocol: TCP
      name: mongo
      port: 27017
      targetPort: 27017
  selector:
    role: mongo