kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: default
  name: teamcloud-video
  labels:
    app: teamcloud-video
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teamcloud-video
  template:
    metadata:
      labels:
        app: teamcloud-video
      annotations:
        timestamp: "{{ now | unixEpoch }}"
    spec:
      containers:
       - name: web
         image: jitsi/web
         ports:
          - name: web
            containerPort: 80
         env:
          - name: JICOFO_AUTH_USER
            value: focus
          - name: XMPP_DOMAIN
            value: meet.jitsi
          - name: XMPP_AUTH_DOMAIN
            value: auth.meet.jitsi
          - name: XMPP_BOSH_URL_BASE
            value: http://prosody:5280
          - name: XMPP_MUC_DOMAIN
            value: muc.meet.jitsi
          - name: TZ
            value: Europe/Paris
          - name: PUBLIC_URL
            value: "https://{ .Values.app.name }}.{{ .Values.app.domain }}"
          - name: SHOW_JITSI_WATERMARK
            value: "false"
          - name: SHOW_WATERMARK_FOR_GUESTS
            value: "false"