kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: default
  name: teamcloud-jvb
  labels:
    app: teamcloud-jvb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teamcloud-jvb
  template:
    metadata:
      labels:
        app: teamcloud-jvb
      annotations:
        timestamp: "{{ now | unixEpoch }}"
    spec:
      containers:
       - name: jvb
         image: jitsi/jvb
         ports:
         - containerPort: 30000
           protocol: UDP
         - containerPort: 30001
         resources: {}
#         restartPolicy: Always
         env:
          - name: XMPP_SERVER
            value: prosody
          - name: DOCKER_HOST_ADDRESS
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: XMPP_DOMAIN
            value: meet.jitsi
          - name: XMPP_AUTH_DOMAIN
            value: auth.meet.jitsi
          - name: JVB_PORT
            value: "30000"
          - name: JVB_TCP_PORT
            value: "30001"
          - name: JVB_AUTH_USER
            value: jvb
          - name: JVB_AUTH_PASSWORD
            value: passw0rd
          - name: JVB_BREWERY_MUC
            value: jvbbrewery
          - name: XMPP_INTERNAL_MUC_DOMAIN
            value: internal-muc.meet.jitsi
          - name: JVB_STUN_SERVERS
            value: stun.l.google.com:19302,stun1.l.google.com:19302,stun2.l.google.com:19302
          - name: JICOFO_AUTH_USER
            value: focus
          - name: TZ
            value: Europe/Paris