apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "teamcloud-nextcloud.name" . }}-nc-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: {{ .Values.storage.limits.data }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "teamcloud-nextcloud.name" . }}-nc-config
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 128Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "teamcloud-nextcloud.name" . }}-nc-apps
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 512Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "teamcloud-nextcloud.name" . }}-nc-themes
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 128Mi
---      
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "teamcloud-nextcloud.name" . }}-nc-db
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: {{ .Values.storage.limits.database }}
---