app:
  name: video
  domain: example.org

  #
  secrets:
    jvb:
      component: "jsdjhjk623sxbnedrtg42315tr"
      auth: "srfddffgjsdf34342349988"
    jicofo:
      component: "s234sdffghbvjnndf!"
      auth: "sdfokjsdfkl123123123ghghg!"